# permissions for end users to view allocations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: allocation-viewer-role
rules:
- apiGroups:
  - myapp.aaron.domain
  resources:
  - allocations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - myapp.aaron.domain
  resources:
  - allocations/status
  verbs:
  - get
