// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"github.com/aaronlyc/allocation/server/internal/svc"

	"github.com/tal-tech/go-zero/rest"
)

func RegisterHandlers(engine *rest.Server, serverCtx *svc.ServiceContext) {
	engine.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/generate/data",
				Handler: GenerateCRDataHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/clean/data",
				Handler: CleanAllHandler(serverCtx),
			},
		},
	)
}
